<section class="base-after-signup-login-support-review">
    <div class="base-core-row">
        <div class="base-after-signup-login-support-review__two-col">
            <div class="base-after-signup-login-support-review__col">
                <div class="base-after-signup-login-support__content">
                    <img src="<?php echo esc_url(plugins_url('assets/icon/icon-support-new.png', PRO_LINKS_PLUGIN_DIRNAME)); ?>"
                         alt="Support">
                    <div class="base-after-signup-login-support-review__des">
                        <h3>Need our support? Let us know, we'll be back shortly!</h3>
                        <a href="https://aitech.asia/contact/" title="Contact Us"
                           target="_blank"
                           class="base-core-button base-core-button--alt-white btn-contact">Contact
                            Us</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
